import = ["~/.config/alacritty/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

dimensions.columns = 179
dimensions.lines = 50
decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14.5

